//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consesionario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public byte Id_Dep { get; set; }
        public string Nom_Dep { get; set; }
    }
}
